package com.cars24.slack_hrbp.request;

import com.cars24.slack_hrbp.data.request.AddLeaveRequest;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

class AddLeaveRequestTest {

    private AddLeaveRequest addLeaveRequest;

    @BeforeEach
    void setUp() {
        addLeaveRequest = new AddLeaveRequest();
    }

    @Test
    void testSetAndGetDate() {
        String testDate = "2024-03-28";
        addLeaveRequest.setDate(testDate);
        assertEquals(testDate, addLeaveRequest.getDate());
    }

    @Test
    void testSetAndGetLeaveType() {
        String testLeaveType = "Annual Leave";
        addLeaveRequest.setLeaveType(testLeaveType);
        assertEquals(testLeaveType, addLeaveRequest.getLeaveType());
    }

    @Test
    void testSetAndGetReason() {
        String testReason = "Family vacation";
        addLeaveRequest.setReason(testReason);
        assertEquals(testReason, addLeaveRequest.getReason());
    }

    @Test
    void testFullConstructorAndGetters() {
        // Create a fully populated AddLeaveRequest
        AddLeaveRequest fullRequest = new AddLeaveRequest();
        fullRequest.setDate("2024-03-28");
        fullRequest.setLeaveType("Annual Leave");
        fullRequest.setReason("Family vacation");

        // Verify all getters
        assertEquals("2024-03-28", fullRequest.getDate());
        assertEquals("Annual Leave", fullRequest.getLeaveType());
        assertEquals("Family vacation", fullRequest.getReason());
    }

    @Test
    void testToString() {
        // Verify that toString() is generated by Lombok
        AddLeaveRequest fullRequest = new AddLeaveRequest();
        fullRequest.setDate("2024-03-28");
        fullRequest.setLeaveType("Annual Leave");
        fullRequest.setReason("Family vacation");

        String toStringResult = fullRequest.toString();
        assertNotNull(toStringResult);
        assertTrue(toStringResult.contains("date=2024-03-28"));
        assertTrue(toStringResult.contains("leaveType=Annual Leave"));
        assertTrue(toStringResult.contains("reason=Family vacation"));
    }

    @Test
    void testEqualsAndHashCode() {
        AddLeaveRequest request1 = new AddLeaveRequest();
        request1.setDate("2024-03-28");
        request1.setLeaveType("Annual Leave");

        AddLeaveRequest request2 = new AddLeaveRequest();
        request2.setDate("2024-03-28");
        request2.setLeaveType("Annual Leave");

        AddLeaveRequest request3 = new AddLeaveRequest();
        request3.setDate("different");

        // Test equals
        assertEquals(request1, request2);
        assertNotEquals(request1, request3);

        // Test hashCode
        assertEquals(request1.hashCode(), request2.hashCode());
        assertNotEquals(request1.hashCode(), request3.hashCode());
    }

}