package com.cars24.slack_hrbp.response;

import com.cars24.slack_hrbp.data.response.EmployeeDisplayResponse;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class EmployeeDisplayResponseTest {
    private EmployeeDisplayResponse employeeDisplayResponse;

    @BeforeEach
    void setUp() {
        employeeDisplayResponse = new EmployeeDisplayResponse();
    }

    @Test
    void testSetAndGetUserId() {
        String testUserId = "user123";
        employeeDisplayResponse.setUserId(testUserId);
        assertEquals(testUserId, employeeDisplayResponse.getUserId());
    }

    @Test
    void testSetAndGetUsername() {
        String testUsername = "john.doe";
        employeeDisplayResponse.setUsername(testUsername);
        assertEquals(testUsername, employeeDisplayResponse.getUsername());
    }

    @Test
    void testSetAndGetEmail() {
        String testEmail = "john.doe@example.com";
        employeeDisplayResponse.setEmail(testEmail);
        assertEquals(testEmail, employeeDisplayResponse.getEmail());
    }

    @Test
    void testFullConstructorAndGetters() {
        // Create a fully populated EmployeeDisplayResponse
        EmployeeDisplayResponse fullResponse = new EmployeeDisplayResponse();
        fullResponse.setUserId("user123");
        fullResponse.setUsername("john.doe");
        fullResponse.setEmail("john.doe@example.com");

        // Verify all getters
        assertEquals("user123", fullResponse.getUserId());
        assertEquals("john.doe", fullResponse.getUsername());
        assertEquals("john.doe@example.com", fullResponse.getEmail());
    }

    @Test
    void testToString() {
        // Verify that toString() is generated by Lombok
        EmployeeDisplayResponse fullResponse = new EmployeeDisplayResponse();
        fullResponse.setUserId("user123");
        fullResponse.setUsername("john.doe");
        fullResponse.setEmail("john.doe@example.com");

        String toStringResult = fullResponse.toString();
        assertNotNull(toStringResult);
        assertTrue(toStringResult.contains("userId=user123"));
        assertTrue(toStringResult.contains("username=john.doe"));
        assertTrue(toStringResult.contains("email=john.doe@example.com"));
    }

    @Test
    void testEqualsAndHashCode() {
        EmployeeDisplayResponse response1 = new EmployeeDisplayResponse();
        response1.setUserId("user123");
        response1.setUsername("john.doe");
        response1.setEmail("john.doe@example.com");

        EmployeeDisplayResponse response2 = new EmployeeDisplayResponse();
        response2.setUserId("user123");
        response2.setUsername("john.doe");
        response2.setEmail("john.doe@example.com");

        EmployeeDisplayResponse response3 = new EmployeeDisplayResponse();
        response3.setUserId("user456");
        response3.setUsername("jane.smith");
        response3.setEmail("jane.smith@example.com");

        // Test equals
        assertEquals(response1, response2);
        assertNotEquals(response1, response3);

        // Test hashCode
        assertEquals(response1.hashCode(), response2.hashCode());
        assertNotEquals(response1.hashCode(), response3.hashCode());
    }

    @Test
    void testNullAndEmptyValues() {
        // Test setting null values
        employeeDisplayResponse.setUserId(null);
        assertNull(employeeDisplayResponse.getUserId());

        employeeDisplayResponse.setUsername(null);
        assertNull(employeeDisplayResponse.getUsername());

        employeeDisplayResponse.setEmail(null);
        assertNull(employeeDisplayResponse.getEmail());

        // Test setting empty values
        employeeDisplayResponse.setUserId("");
        assertEquals("", employeeDisplayResponse.getUserId());

        employeeDisplayResponse.setUsername("");
        assertEquals("", employeeDisplayResponse.getUsername());

        employeeDisplayResponse.setEmail("");
        assertEquals("", employeeDisplayResponse.getEmail());
    }
}